### ISSUE TITLE
Captions Background

### ISSUE THREAD

**Issue by cmwonn** [recloudstream/recloudstream.github.io#5]
Cut background subtitles if the lines are Little too high to this:
![Screenshot_2022-08-07-23-28-17-96_2c2851f616de21a6da6fb44c83a25e93~2](https://user-images.githubusercontent.com/111416424/185053723-75dc9a1b-32ea-4339-ad2d-df199bf3f31a.jpg)

cloudstream:
![IMG_20220817_145436](https://user-images.githubusercontent.com/111416424/185054350-721fdc7f-9660-4f72-b6fb-3876bd1df90e.jpg)

**Comment by MustardChef** [comment]
> Cut background subtitles if the lines are Little too high to this: ![Screenshot_2022-08-07-23-28-17-96_2c2851f616de21a6da6fb44c83a25e93~2](https://user-images.githubusercontent.com/111416424/185053723-75dc9a1b-32ea-4339-ad2d-df199bf3f31a.jpg)
> 
> cloudstream: ![IMG_20220817_145436](https://user-images.githubusercontent.com/111416424/185054350-721fdc7f-9660-4f72-b6fb-3876bd1df90e.jpg)

I don't think this is the correct place to request this. Join the Discord or start and issue here https://github.com/recloudstream/cloudstream/issues

**Comment by C10udburst** [comment]
yeah as stated above, wrong place for issues
